### ISSUE TITLE
What pull request triggered the Action?

### ISSUE THREAD

**Issue by stuartpurgavie** [lmasaya/pagerduty-notifier-action#7]
I would like to see the Pull Request number that triggered the action somewhere in the request, at a minimum. On a busy repository it can be impossible to draw a 1:1 link between a given PR and the PagerDuty incident based only on the name of the repository and the name of the submitter.

Ideally, this would be presented as a fully formed URL / URI so that searching would not be necessary.

**Comment by lmasaya** [comment]
This was solved by https://github.com/lmasaya/pagerduty-notifier-action/pull/8.
